name: Checkout 
on: push
jobs:
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before
        run: ls -a
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: List files After
        run: ls -a