name: Default Branch Workflow
on:
  push:
    branches:
      - $default-branch
jobs:
  job-one:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    # Add your workflow steps here
