name: Default Branch Workflow
on:
  push:
    branches:
      - $default-branch
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    # Add your workflow steps here
