name: Initial Work flow
on: 
  push: 
    branches: 
    - main
jobs:
  Build-Job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Build the aplications
      run: echo "Building the application"
