name: Multi Jobs Workflow
on: push
jobs:
  build-job-1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y
    - name: Execute Cowsay Command
      run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
    - name: Sleep for 30 seconds
      run: sleep 30
# Each job will run on their own machine.
  test-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10
      - name: Test file exists
        run: grep -i "dragon" dragon.txt
  deploy-job-3:
    runs-on: ubuntu-latest
    steps:
      - name: Read File
        run: cat dragon.txt
      - name: Deploying
        run: echo Deploying!!!!

# 3 jobs run in parallel, and no job will wait for other jobs 

# we want build job to be executed first, followed by other 2 jobs 
# but there is not guarentty that build job will execute first. 
