name: Events Work Flow 
on: [push, pull_request, issues]
#run-name: Run by ${{ github.actor }} on commit ${{ github.sha }} in branch ${{ github.ref }}
run-name: Run by ${{ github.actor }} in branch ${{ github.ref }}
jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - name: General Step
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - name: Checkout the repo 
        uses: actions/checkout@v4
