name: Parallel-Depend-Job
on: push
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Welcome Siva!!!!"
      - name: Multi Line 
        run: |
          npm -v
          node -v
  parallel-job-macos: 
    runs-on: macos-latest
    steps:
      - name: MAC SW Version
        run: sw_vers
  dependent-job:
    needs: build-job
    runs-on: windows-latest
    steps:
      - name: echo a string in windows
        run: Write-Output "Windows String"
      - name: Error Step
        run: doesnotexits