name: Script Work Flow
on: push
jobs:
  ScriptJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout REPO
        uses: actions/checkout@v4
      - name: Executing Schell Script 
        run: ./ascii.sh