name: Script Work Flow
on: push
jobs:
  ScriptJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout REPO
        uses: actions/checkout@v4
      - name: Changing Permissions
        run: chmod +x ascii.sh
      - name: Executing Schell Script 
        run: ./ascii.sh
    #   - name: Change and Execute Script
    #     run: |
    #       chmod +x ascii.sh
    #       ./ascii.sh
    # ctrl+/