name: Second Work Flow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: List mulitple steps
          run: |
            echo "My First Github action"
            ls -ltr
            cat README.md
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
        # - name: list files
        #   run: ls
        # - name: Read File
        #   run: cat 