name: Upload Download WorkFlow
on: push
jobs:
    build-job-1:
      runs-on: ubuntu-latest
      steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y
      - name: Execute Cowsay Command
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
      - name: Upload Dragon Text file
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dragon.txt
    test-job-2:
      needs: build-job-1 # Can be list as well
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v4
          with: 
            name: my-artifact
            path: dragon.txt
          name: Downloading artifact
        - name: Test file exists
          run: grep -i "dragon" dragon.txt

    deploy-job-3:
      needs: [test-job-2]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v4
          with: 
            name: my-artifact
            path: dragon.txt
          name: Downloading artifact
  