# Env variables can be stored at the 
    # step level
    # job level
    # workflow level
name: Exploring Vars and Secrets
on: push
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: i27k8s10
    IMAGE_NAME: github-action-nginx 
jobs:
######################## Environment Variables at the Step Level ########################
#   Docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Build 
#         env:
#           CONTAINER_REGISTRY: docker.io
#           DOCKER_USERNAME: i27k8s10
#           IMAGE_NAME: github-action-nginx
#           # we can refer env variables in 2 ways 
#           # $ENVNAME
#           # ${{ env.ENVNAME }}
#         run: docker build -t $CONTAINER_REGISTRY/${{ env.CONTAINER_REGISTRY }}/$IMAGE_NAME:latest
#       - name: Docker Login
#         env:
#           DOCKER_USERNAME: i27k8s10
#           DOCKER_PSW: Gcp@20232023
#         run: docker login --username=${{ env.DOCKER_USERNAME }} --password=${{ env.DOCKER_PSW}} 
#       - name: Docker Publish
#         env:
#           DOCKER_USERNAME: i27k8s10
#           IMAGE_NAME: github-action-nginx
#         run: docker push docker.io/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
#   Docker-Deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy
#         env:
#           CONTAINER_REGISTRY: docker.io
#           DOCKER_USERNAME: i27k8s10
#           IMAGE_NAME: github-action-nginx
#         run: docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest 


######################## Environment Variables at the Job Level ########################
    Docker:
      env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: i27k8s10
        IMAGE_NAME: github-action-nginx 
      runs-on: ubuntu-latest
      steps:
        - name: Docker Build 
            # we can refer env variables in 2 ways 
            # $ENVNAME
            #${{ env.ENVNAME }}
          run: docker build -t $CONTAINER_REGISTRY/${{ env.CONTAINER_REGISTRY }}/$IMAGE_NAME:latest
        - name: Docker Login
          env:
            DOCKER_PSW: Gcp@20232023
          run: docker login --username=${{ env.DOCKER_USERNAME }} --password=${{ env.DOCKER_PSW}} 
        - name: Docker Publish
          run: docker push docker.io/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
    Docker-Deploy:
        needs: Docker
       # env:
        #    CONTAINER_REGISTRY: docker.io
         #   DOCKER_USERNAME: i27k8s10
          #  IMAGE_NAME: github-action-nginx 
        runs-on: ubuntu-latest
        steps:
        - name: Deploy
          run: docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest 