name: Working Dir and Shells
on: push
defaults:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
  run:
    shell: bash
jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Displaying Working Directory and list files
        run: |
          echo "********* Displaying the Present Working Directory *********"
          pwd
          echo "********* Displaying the List of file *********"
          ls -la
          echo "********* Printing few default env variables *********"
          echo $GITHUB_SHA
          echo $GITHUB_WORKSPACE
          echo $GITHUB_REPOSITORY
  display-wd-info-windows:
    runs-on:  windows-latest
    steps:
    - name: Displaying Working Directory and list files
      run: |
        Get-Location
        dir
        echo $env:GITHUB_SHA
        echo $env:GITHUB_REPOSITORY
        echo $env:GITHUB_WORKSPACE
    # - name: Displaying Working Directory and list files
    #   run: |
    #     echo "********* Displaying the Present Working Directory *********"
    #     pwd
    #     echo "********* Displaying the List of file *********"
    #     ls -la
    #     echo "********* Printing few default env variables *********"
    #     echo $GITHUB_SHA
    #     echo $GITHUB_WORKSPACE
    #     echo $GITHUB_REPOSITORY